### ISSUE TITLE
RunWhatsApp

### ISSUE THREAD

**Issue by SunboX** [mozilla/pluotsorbet#1668]
Great that there's a client now. But two things are really disturbing:
* it is very slooow on a Nexus 4 running latest Spark
* it looks very blurry

Doesn't make fun to use it. You have to wait some seconds on a high end phone every time you touch something.

But at the end, great work. Not really usable now, but great to see that it's basically working. :+1:

**Comment by mykmelez** [comment]
@SunboX: what in particular was slow? Was it startup, responsiveness to input (like taps), or runtime performance generally? These can have different causes, so just trying to understand what you're seeing.

As for the blurriness, it's a hard problem to solve, as J2ME doesn't appear to have been designed for HiDPI screens, but I've been experimenting over in #1642, and @TimAbraldes and @brendandahl have also been thinking about it.

**Comment by SunboX** [comment]
The first startup is slow, but that's ok. More frustrating is the "responsiveness" after inputs. Often the chat message won't send. Or I have to re-start the whole app to receive new messages. The delay after a press on chat messages, or the people select, the scrolling inside the people list ... a.s.o. is very frustrating.
At all it works, but I don't want to use it (because of the delays).

Would be nice if it get's a bit more sharp. ;) It feels cheap/unfinished compared to other web apps. ;)

But at the end - really great work! Love it. :)

**Comment by mykmelez** [comment]
> More frustrating is the "responsiveness" after inputs. Often the chat message won't send.

I think this is actually an event dispatch issue rather than a responsiveness issue. I see it too, including on high-end devices where the UI is otherwise quite responsive. I filed issue #1669 on it.

> Or I have to re-start the whole app to receive new messages.

Hmm, I don't think I've seen this before, although I've seen delays in receiving new messages, including after leaving airplane mode. I filed #1670 to track this issue.

> The delay after a press on chat messages, or the people select, the scrolling inside the people list ... a.s.o. is very frustrating.

Scrolling is #845 (#1422 may also make a difference there).

Regarding the delay after pressing on chat messages, do you mean a delay when tapping on a conversation in the list of conversations (before you see the conversation view), or do you mean a delay when tapping a message in the conversation view (before the Forward button appears)?

Tapping on a conversation in the list of conversations used to be quite slow, but it's been relatively fast lately, at least on the hardware I've tested. It does sometimes take multiple taps, however, and I filed issue #1671 on that.

> At all it works, but I don't want to use it (because of the delays).
> 
> Would be nice if it get's a bit more sharp. ;) It feels cheap/unfinished compared to other web apps. ;)

Sure, I certainly understand that. Our goal is to make it possible to run WhatsApp and many other midlets on PluotSorbet, and for them to behave correctly and perform well. And we know that we're not quite there yet. But we don't always know about the specific problems. So I really appreciate your input, even though you're reporting problems!

> But at the end - really great work! Love it. :)

Thanks, I appreciate it! I'm going to close this issue in favor of tracking each of the problems in its own issue, as referenced above. Please watch those issues for updates on our efforts to resolve them, and let us know if you experience any other issues!
